{% set name = "Janome" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce4a3ed7a4635c2f80139639327d5b1e0381858ad74a3c4a61e8cc83f820400e

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - janome
    - janome.sysdic
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mocobeta/janome
  summary: Japanese morphological analysis engine.
  license: Apache-2.0
  license_file:
    - LICENSE.txt
    - NOTICE.txt
  doc_url: https://mocobeta.github.io/janome/en/
  dev_url: https://github.com/mocobeta/janome/wiki#for-contributors

extra:
  recipe-maintainers:
    - BastianZim
